Fix upgrading guide.
terraform-google-modules/terraform-google-gsuite-export pull request #16
Opened 2019-11-27 07:31 UTC by omazin

2019-11-27 20:46 UTC, aaron-lane requested changes
Thanks @omazin!

2019-11-27 20:46 UTC, aaron-lane commented on README.md
>  The current version is 2.X. The following guides are available to assist with upgrades:
This statement should be fixed as well.
```suggestion
The current version is 1.X. The following guides are available to assist with upgrades:
```

2019-11-27 20:46 UTC, aaron-lane commented on README.md
> +- [1.X -> 2.0](./docs/upgrading_to_gsuite_export_v1.0.md)
```suggestion
- [0.X -> 1.0](./docs/upgrading_to_gsuite_export_v1.0.md)
```

2019-11-28 09:21 UTC, omazin commented on README.md
> +- [1.X -> 2.0](./docs/upgrading_to_gsuite_export_v1.0.md)
good catch

2019-11-28 15:43 UTC, aaron-lane approved these changes

2019-11-28 15:43 UTC, merged